### ISSUE TITLE
refactor: 이력서 서비스 서버를 분리한다.

### ISSUE THREAD

**Issue by waveofmymind** [waveofmymind/GoodJob#295]
## TODO

- [x] 메인 서버의 요청으로부터 카프카로 메시지를 발송하면, 이력서 서버에서 메시지를 처리한다.
- [ ] 메인 서버에서 resume-domain 모듈을 제거하는 것이 최종 목적
- [ ] 이력서 정보를 조회할 경우, Feign을 활용한 REST 통신으로 정보를 가져올 수 있다.
